export const actionType = {
  SET_APP_LANGUAGE: 'SET_APP_LANGUAGE',
  TOGGLE_SIDE_MENU: 'TOGGLE_SIDE_MENU',
  ADD_CLINIC: 'ADD_CLINIC',
  EDIT_CLINIC: 'EDIT_CLINIC',
  SET_CLINICS: 'SET_CLINICS',
  ADD_USER: 'ADD_USER',
  EDIT_USER: 'EDIT_USER',
  SET_USERS: 'SET_USERS',
  BOOK_APPOINTMENT: 'BOOK_APPOINTMENT',
  ACTIVATE_APPOINTMENT: 'ACTIVE_APPOINTMENT',
  DEACTIVATE_APPOINTMENT:'DEACTIVATE_APPOINTMENT'
}
